// Post a blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "I love Paris!",
    "author": "Gary",
    "url": "www.paris.fr",
    "likes": 10,
    "userId": "66a5312f2a81c3e07fe556f6"
}

#####
// Post a user
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "zelenskyi0125",
    "name": "zelenskyi",
    "password": "crimea"
}

#####
// Get a blog
GET http://localhost:3003/api/blogs/66a5362b833b78be32dbe630

#####
// Get all blogs
GET http://localhost:3003/api/blogs/

#####
// Get all users
Get http://localhost:3003/api/users




#####
// Delete a blog
Delete http://localhost:3003/api/blogs/66a53555d3eb73678ef55b74
