GET http://localhost:3001/api/notes/

###

POST http://localhost:3001/api/notes 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2YTI5YTY4MzNiMDkwNDU0ODAyM2FiNyIsImlhdCI6MTcyMjA5NDk3Nn0.0fOIHap3p-ekxNH0PW6oZF7Xlz6Up_6MrrSxT7FQrjc

// Before Content-Type: application/json: No EMPTY LINE; 
// after: ONE EMPTY line
{
"content": "I love Paris", 
"important": true,
"userId": "66a29a6833b0904548023ab7"
}

### 
DELETE http://localhost:3001/api/notes/6697ed414f4306c0d585d0d4

###

PUT http://localhost:3001/api/notes/6698174088ff079887e57e09
Content-Type: application/json

{
    "content": "rest client is not cool",
    "important": true
}
