POST http://localhost:3001/api/users
Content-Type: application/json

// Before Content-Type: application/json: No EMPTY LINE; 
// after: ONE EMPTY line
{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}
###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "root",
    "password": "salainen"
}